cargo-features = [ "default-run" ]

[package]
name = "urusai"
version = "0.1.0"
authors = [ "Kazakuri <kazakuri@urus.ai>" ]
edition = "2018"
default-run = "urusai"

[[bin]]
name = "urusai"
path = "src/main.rs"

[[bin]]
name = "urusai_worker"
path = "src/worker/main.rs"

[lib]
name = "urusai_lib"
path = "src/lib.rs"

[dependencies]
urusai_codegen = { path = "urusai_codegen" }
actix = "0.7"
actix-web = "1.0.0-beta.1"
actix-files = "0.1.0-betsa.1"
actix-session = "0.1.0-beta.1"
actix-service = "0.1.0-beta.1"
actix-server-config = "0.1.1"
bytes = "0.4.11"
diesel = { version = "1.4.0", features = [ "postgres", "extras" ] }
dotenv = "0.9.0"
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5.1"
uuid = { version = ">=0.2.0, <0.7.0", features = [ "v4", "serde" ] }
futures = "0.1"
sodiumoxide = "0.2.0"
log = "0.4.6"
env_logger = "0.6.0"
failure = "*"
askama = "0.7"
nanoid = "0.2.0"
r2d2 = "0.8.3"
regex = "1"
lazy_static = "1.2.0"
lettre = "0.8"
lettre_email = "0.8"
faktory = "0.10.5"
native-tls = "0.1.5"

[build-dependencies]
askama = "0.7"

[features]
default = ["mq"]

mq = []
