[package]
name = "urusai_codegen"
version = "0.1.0"
authors = [ "Matt Wilmink <wilmink@gdls.com>" ]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.14.4"
heck = "0.3.1"
proc-macro2 = "0.4.24"
quote = "0.6.3"
